# Generated by Django 4.2.2 on 2023-06-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ae3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
